### ISSUE TITLE
The field is required if using betweenLength rule.

### ISSUE THREAD

**Issue by lukasborawski** [cj/vuelidation#3]
As above, when i'm using rule for `betweenLength` the field is automatically required...

**Comment by cj** [comment]
@lukasborawski that's because if the field is empty and you have `betweenLength: { min: 1, max: 10 }`, the field would be invalid as the current length is 0, so it's functioning correctly.

I could add an `allowEmpty: true`, or `ignoreEmpty: true` option so that it would ignore empty fields.

Would that work for you?

**Comment by cj** [comment]
@lukasborawski for now you could just do:

```javascript
betweenLength: {
  min: 5,
  max: 10,
  if () { return this.someField }
}
```

**Comment by lukasborawski** [comment]
@cj thx it's work fine
